import { useState } from 'react';
import { CalendarClock, FileHeart, Gauge, TriangleAlert } from 'lucide-react';
import { DataError, Empty, Field, Loading, Modal, PageHeader, Status } from '@/components/ui';
import { type Row, useCreateRow, useRows, useUpdateRow } from '@/lib/data';

function CarePlanForm({people,record,sections,onClose}:{people:Row[];record?:Row|undefined;sections:Row[];onClose:()=>void}){
 const create=useCreateRow('care_plans');const update=useUpdateRow('care_plans');const createSection=useCreateRow('care_plan_sections');const updateSection=useUpdateRow('care_plan_sections');const mutation=record?update:create;const ownSections=record?sections.filter(x=>x.care_plan_id===record.id):[];
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));const {section_heading,section_content,...plan}=values;const saved=await mutation.mutateAsync(record?{id:record.id,...plan}:plan);if(section_heading)await createSection.mutateAsync({care_plan_id:record?.id??saved.id,section_key:String(section_heading).toLowerCase().replace(/[^a-z0-9]+/g,'_'),heading:section_heading,content:section_content,sort_order:ownSections.length});onClose()}
 async function saveSection(e:React.FormEvent<HTMLFormElement>,id:string){e.preventDefault();await updateSection.mutateAsync({id,...Object.fromEntries(new FormData(e.currentTarget))})}
 return <><form className="form-grid" onSubmit={submit}><Field label="Person supported"><select name="service_user_id" defaultValue={record?.service_user_id??''} required disabled={Boolean(record)}><option value="" disabled>Select a person</option>{people.filter(x=>x.status==='active').map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Title"><input name="title" defaultValue={record?.title??'Care and support plan'} required/></Field><Field label="Status"><select name="status" defaultValue={record?.status??'draft'}><option value="draft">Draft</option><option value="active">Active</option><option value="superseded">Superseded</option><option value="archived">Archived</option></select></Field><Field label="Version"><input name="version" type="number" min="1" defaultValue={record?.version??1} required/></Field><Field label="Effective from"><input name="effective_from" type="date" defaultValue={record?.effective_from??''}/></Field><Field label="Review due"><input name="review_due" type="date" defaultValue={record?.review_due??''}/></Field><Field label="Summary"><textarea name="summary" defaultValue={record?.summary??''}/></Field><Field label="Outcomes"><textarea name="outcomes" defaultValue={record?.outcomes??''}/></Field><Field label="Preferences"><textarea name="preferences" defaultValue={record?.preferences??''}/></Field><Field label={record?'Add section heading':'First section heading'}><input name="section_heading" placeholder="Personal care, nutrition, communication…"/></Field><Field label="Section content"><textarea name="section_content"/></Field>{(mutation.error||createSection.error)&&<p className="form-error">{(mutation.error||createSection.error)?.message}</p>}<div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn primary" disabled={mutation.isPending||createSection.isPending}>{mutation.isPending?'Saving…':'Save care plan'}</button></div></form>{record&&ownSections.length>0&&<section className="care-plan-sections"><h3>Plan sections</h3>{ownSections.map(section=><form key={section.id} onSubmit={e=>void saveSection(e,section.id)}><input name="heading" defaultValue={section.heading}/><textarea name="content" defaultValue={section.content??''}/><button className="btn small">Save section</button></form>)}{updateSection.error&&<p className="form-error">{updateSection.error.message}</p>}</section>}</>
}

function RiskForm({people,employees,record,onClose}:{people:Row[];employees:Row[];record?:Row|undefined;onClose:()=>void}){
 const create=useCreateRow('risk_assessments');const update=useUpdateRow('risk_assessments');const mutation=record?update:create;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));await mutation.mutateAsync(record?{id:record.id,...values}:values);onClose()}
 return <form className="form-grid" onSubmit={submit}><Field label="Person supported"><select name="service_user_id" defaultValue={record?.service_user_id??''} required disabled={Boolean(record)}><option value="" disabled>Select a person</option>{people.filter(x=>x.status==='active').map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Category"><input name="category" defaultValue={record?.category??''} placeholder="Falls, medication, environment…" required/></Field><Field label="Hazard"><textarea name="hazard" defaultValue={record?.hazard??''} required/></Field><Field label="Who is at risk"><input name="who_at_risk" defaultValue={record?.who_at_risk??''}/></Field><Field label="Likelihood (1–5)"><input name="likelihood" type="number" min="1" max="5" defaultValue={record?.likelihood??1} required/></Field><Field label="Severity (1–5)"><input name="severity" type="number" min="1" max="5" defaultValue={record?.severity??1} required/></Field><Field label="Controls"><textarea name="controls" defaultValue={record?.controls??''}/></Field><Field label="Owner"><select name="owner_id" defaultValue={record?.owner_id??''}><option value="">Unassigned</option>{employees.filter(x=>x.status==='active').map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Review due"><input name="review_due" type="date" defaultValue={record?.review_due??''}/></Field><Field label="Status"><select name="status" defaultValue={record?.status??'open'}><option value="open">Open</option><option value="controlled">Controlled</option><option value="closed">Closed</option></select></Field>{mutation.error&&<p className="form-error">{mutation.error.message}</p>}<div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn primary" disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Save assessment'}</button></div></form>
}

export function CarePage(){
 const [tab,setTab]=useState<'plans'|'risks'>('plans');const [creating,setCreating]=useState(false);const [selected,setSelected]=useState<Row|null>(null);const plans=useRows('care_plans','review_due',true);const sections=useRows('care_plan_sections','sort_order',true);const risks=useRows('risk_assessments','review_due',true);const people=useRows('service_users','full_name',true);const employees=useRows('employees','full_name',true);const q=tab==='plans'?plans:risks;
 const close=()=>{setCreating(false);setSelected(null)};
 return <><PageHeader title="Care plans & risk" description="Person-centred plans, outcomes, reviews and risk controls." action={tab==='plans'?'New care plan':'New assessment'} onAction={()=>setCreating(true)}/><div className="toolbar"><div className="tabs"><button className={tab==='plans'?'active':''} onClick={()=>setTab('plans')}><FileHeart/>Care plans</button><button className={tab==='risks'?'active':''} onClick={()=>setTab('risks')}><TriangleAlert/>Risk assessments</button></div></div>{q.isLoading?<Loading/>:q.error?<DataError message={q.error.message}/>:q.data?.length===0?<Empty text={tab==='plans'?'No care plans created':'No risk assessments created'}/>:tab==='plans'?<div className="record-grid">{plans.data?.map(p=><article className="record-card clickable" key={p.id} onClick={()=>setSelected(p)}><header><span className="record-icon blue"><FileHeart/></span><Status value={p.status}/></header><h3>{p.service_user?.full_name}</h3><p>{p.title} • Version {p.version}</p><blockquote>{p.summary||'No plan summary recorded.'}</blockquote><footer><span><CalendarClock/>Review {p.review_due?new Date(p.review_due).toLocaleDateString('en-GB'):'not set'}</span><button onClick={()=>setSelected(p)}>Open plan</button></footer></article>)}</div>:<div className="table-card"><table><thead><tr><th>Person</th><th>Category / hazard</th><th>Risk score</th><th>Controls</th><th>Review</th><th>Status</th><th></th></tr></thead><tbody>{risks.data?.map(r=><tr key={r.id} className="clickable" onClick={()=>setSelected(r)}><td><strong>{r.service_user?.full_name}</strong></td><td><strong>{r.category}</strong><small>{r.hazard}</small></td><td><span className={`risk-score score-${r.likelihood*r.severity}`}><Gauge/>{r.likelihood*r.severity}</span></td><td>{r.controls}</td><td>{r.review_due?new Date(r.review_due).toLocaleDateString('en-GB'):'—'}</td><td><Status value={r.status}/></td><td><button className="link-btn">Open</button></td></tr>)}</tbody></table></div>}{(creating||selected)&&<Modal title={tab==='plans'?(selected?'Edit care plan':'New care plan'):(selected?'Edit risk assessment':'New risk assessment')} onClose={close}>{tab==='plans'?<CarePlanForm people={people.data??[]} sections={sections.data??[]} record={selected??undefined} onClose={close}/>:<RiskForm people={people.data??[]} employees={employees.data??[]} record={selected??undefined} onClose={close}/>}</Modal>}</>
}
