import { AlertTriangle, CalendarCheck, Clock3, Pill, ShieldAlert, UserRoundCheck, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from 'recharts';
import { useAuth } from '@/lib/authContext';
import { useDashboardMetrics, useRows } from '@/lib/data';
import { DataError, Empty, Loading, StatCard, Status } from '@/components/ui';

const time=(value:string)=>new Date(value).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
const dayKey=(value:Date|string)=>new Date(value).toLocaleDateString('en-CA');
const go=(page:string)=>{location.hash=`/${page}`};

export function DashboardPage(){
 const {displayName}=useAuth();const metrics=useDashboardMetrics();const visits=useRows('visits','starts_at',true);const incidents=useRows('incidents','occurred_at',false);const mar=useRows('mar_entries','scheduled_for',false);const plans=useRows('care_plans','review_due',true);
 if(metrics.isLoading)return <Loading/>;if(metrics.error)return <DataError message={metrics.error.message}/>;
 const m=metrics.data??{service_users:0,employees:0,visits_today:0,completed_today:0,open_incidents:0,medication_exceptions:0};
 const today=dayKey(new Date());const todayVisits=(visits.data??[]).filter(v=>dayKey(v.starts_at)===today);const completion=m.visits_today?Math.round((m.completed_today/m.visits_today)*100):0;
 const weekStart=new Date();weekStart.setHours(0,0,0,0);weekStart.setDate(weekStart.getDate()-((weekStart.getDay()+6)%7));
 const weekly=Array.from({length:7},(_,index)=>{const date=new Date(weekStart);date.setDate(date.getDate()+index);const rows=(visits.data??[]).filter(v=>dayKey(v.starts_at)===dayKey(date));return {day:date.toLocaleDateString('en-GB',{weekday:'short'}),planned:rows.length,completed:rows.filter(v=>v.status==='completed').length}});
 const duePlans=(plans.data??[]).filter(p=>p.review_due&&new Date(p.review_due)<=new Date(Date.now()+30*86400000)&&p.status!=='archived');
 const exceptions=(mar.data??[]).filter(e=>dayKey(e.scheduled_for)===today&&e.outcome!=='given');
 return <><div className="welcome"><div><p>{new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</p><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, {displayName.split(' ')[0]}</h1><span>Here’s what’s happening across your care service today.</span></div><div className="quality-score"><strong>{completion}%</strong><span>Visit completion today</span><small>{m.completed_today} of {m.visits_today} visits completed</small></div></div>
 <section className="stats-grid"><StatCard label="Visits today" value={m.visits_today} hint={`${m.completed_today} completed`} icon={<CalendarCheck/>}/><StatCard label="People supported" value={m.service_users} hint="Active records" icon={<UserRoundCheck/>} color="green"/><StatCard label="Care team" value={m.employees} hint="Active employees" icon={<Users/>} color="purple"/><StatCard label="Open incidents" value={m.open_incidents} hint="Requires review" icon={<ShieldAlert/>} color="amber"/></section>
 <div className="dashboard-grid"><section className="panel visits-panel"><header><div><h2>Today’s visits</h2><p>Live schedule and progress</p></div><button className="link-btn" onClick={()=>go('rota')}>Open rota →</button></header>{visits.isLoading?<Loading/>:todayVisits.length?<div className="visit-list">{todayVisits.slice(0,5).map(v=><article key={v.id}><span className="visit-time">{time(v.starts_at)}</span><span className="person-dot">{v.service_user?.full_name?.charAt(0)}</span><div><strong>{v.service_user?.full_name}</strong><small>{v.visit_type} • {v.employee?.full_name||'Unallocated'}</small></div><Status value={v.status}/></article>)}</div>:<Empty text="No visits scheduled today"/>}</section>
 <section className="panel"><header><div><h2>Visit delivery</h2><p>Planned against completed this week</p></div></header><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={weekly} barGap={3}><CartesianGrid vertical={false} stroke="#edf1f3"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="planned" fill="#dce8ee" radius={[4,4,0,0]}/><Bar dataKey="completed" fill="#2c6e8e" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><div className="legend"><span><i className="planned"/>Planned</span><span><i className="completed"/>Completed</span></div></section></div>
 <div className="dashboard-grid lower"><section className="panel"><header><div><h2>Attention required</h2><p>Priority items across the service</p></div></header><div className="attention-list"><article><span className="attention-icon red"><Pill/></span><div><strong>{exceptions.length} medication exception{exceptions.length===1?'':'s'} today</strong><small>{exceptions.length?exceptions.map(x=>x.service_user?.full_name).filter(Boolean).join(', '):'No exceptions recorded'}</small></div><button onClick={()=>go('medication')}>Review</button></article><article><span className="attention-icon amber"><Clock3/></span><div><strong>{duePlans.length} care plan review{duePlans.length===1?'':'s'} due</strong><small>Due within the next 30 days</small></div><button onClick={()=>go('care')}>View</button></article><article><span className="attention-icon yellow"><AlertTriangle/></span><div><strong>{m.open_incidents} open incident{m.open_incidents===1?'':'s'}</strong><small>{(incidents.data??[]).filter(i=>i.status!=='closed'&&(i.severity==='high'||i.severity==='critical')).length} high or critical</small></div><button onClick={()=>go('incidents')}>Review</button></article></div></section>
 <section className="panel"><header><div><h2>Recent incidents</h2><p>Latest recorded events</p></div></header>{incidents.data?.length?<div className="compact-list">{incidents.data.slice(0,3).map(i=><article key={i.id}><span className={`severity ${i.severity}`}/><div><strong>{i.incident_type}</strong><small>{i.service_user?.full_name||'No person linked'} • {new Date(i.occurred_at).toLocaleDateString('en-GB')}</small></div><Status value={i.status}/></article>)}</div>:<Empty text="No incidents recorded"/>}</section></div></>
}
