import { useState } from 'react';
import { LockKeyhole, ShieldAlert, Siren } from 'lucide-react';
import { DataError, Empty, Field, Loading, Modal, PageHeader, Status } from '@/components/ui';
import { type Row, useCreateRow, useRows, useUpdateRow } from '@/lib/data';

const nowInput=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};

function IncidentForm({people,record,onClose}:{people:Row[];record?:Row|undefined;onClose:()=>void}){
 const create=useCreateRow('incidents');const createAction=useCreateRow('incident_actions');const update=useUpdateRow('incidents');const mutation=record?update:create;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));const {follow_up_action,action_due_date,...incident}=values;const saved=await mutation.mutateAsync(record?{id:record.id,...incident,regulator_notifiable:incident.regulator_notifiable==='true'}:{...incident,regulator_notifiable:incident.regulator_notifiable==='true'});if(follow_up_action)await createAction.mutateAsync({incident_id:record?.id??saved.id,action:follow_up_action,due_date:action_due_date});onClose()}
 return <form className="form-grid" onSubmit={submit}><Field label="Person supported (optional)"><select name="service_user_id" defaultValue={record?.service_user_id??''} disabled={Boolean(record)}><option value="">No person linked</option>{people.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Incident type"><input name="incident_type" defaultValue={record?.incident_type??''} required/></Field><Field label="Occurred at"><input name="occurred_at" type="datetime-local" defaultValue={record?.occurred_at?record.occurred_at.slice(0,16):nowInput()} required/></Field><Field label="Location"><input name="location" defaultValue={record?.location??''}/></Field><Field label="Severity"><select name="severity" defaultValue={record?.severity??'low'}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></Field><Field label="Status"><select name="status" defaultValue={record?.status??'open'}><option value="open">Open</option><option value="investigating">Investigating</option><option value="actions_pending">Actions pending</option><option value="closed">Closed</option></select></Field><Field label="Description"><textarea name="description" defaultValue={record?.description??''} required/></Field><Field label="Immediate action"><textarea name="immediate_action" defaultValue={record?.immediate_action??''}/></Field><Field label="Regulator notifiable"><select name="regulator_notifiable" defaultValue={String(record?.regulator_notifiable??false)}><option value="false">No</option><option value="true">Yes</option></select></Field><Field label="Add follow-up action"><textarea name="follow_up_action" placeholder="Optional action to track"/></Field><Field label="Action due date"><input name="action_due_date" type="date"/></Field>{(mutation.error||createAction.error)&&<p className="form-error">{(mutation.error||createAction.error)?.message}</p>}<div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn primary" disabled={mutation.isPending||createAction.isPending}>{mutation.isPending?'Saving…':'Save incident'}</button></div></form>
}

function SafeguardingForm({people,record,onClose}:{people:Row[];record?:Row|undefined;onClose:()=>void}){
 const create=useCreateRow('safeguarding_records');const update=useUpdateRow('safeguarding_records');const mutation=record?update:create;
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));await mutation.mutateAsync(record?{id:record.id,...values}:values);onClose()}
 return <form className="form-grid" onSubmit={submit}><Field label="Person supported"><select name="service_user_id" defaultValue={record?.service_user_id??''} required disabled={Boolean(record)}><option value="" disabled>Select a person</option>{people.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Concern type"><input name="concern_type" defaultValue={record?.concern_type??''} required/></Field><Field label="Risk level"><select name="risk_level" defaultValue={record?.risk_level??'low'}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="immediate">Immediate</option></select></Field><Field label="Status"><select name="status" defaultValue={record?.status??'open'}><option value="open">Open</option><option value="referred">Referred</option><option value="investigating">Investigating</option><option value="closed">Closed</option></select></Field><Field label="Concern details"><textarea name="concern_details" defaultValue={record?.concern_details??''} required/></Field><Field label="Local authority reference"><input name="local_authority_ref" defaultValue={record?.local_authority_ref??''}/></Field><Field label="Police reference"><input name="police_ref" defaultValue={record?.police_ref??''}/></Field><Field label="Outcome"><textarea name="outcome" defaultValue={record?.outcome??''}/></Field>{mutation.error&&<p className="form-error">{mutation.error.message}</p>}<div className="form-actions"><button type="button" className="btn" onClick={onClose}>Cancel</button><button className="btn primary" disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Save safeguarding record'}</button></div></form>
}

export function IncidentsPage(){
 const [tab,setTab]=useState<'incidents'|'safeguarding'>('incidents');const [creating,setCreating]=useState(false);const [selected,setSelected]=useState<Row|null>(null);const incidents=useRows('incidents','occurred_at',false);const actions=useRows('incident_actions','created_at',false);const updateAction=useUpdateRow('incident_actions');const safeguarding=useRows('safeguarding_records','created_at',false);const people=useRows('service_users','full_name',true);const query=tab==='incidents'?incidents:safeguarding;const rows=query.data;const close=()=>{setCreating(false);setSelected(null)};
 return <><PageHeader title="Incidents & safeguarding" description="Record, investigate and evidence your response to concerns." action={tab==='incidents'?'Report incident':'Record concern'} onAction={()=>setCreating(true)}/><div className="toolbar"><div className="tabs"><button className={tab==='incidents'?'active':''} onClick={()=>{setTab('incidents');setSelected(null)}}><Siren/>Incidents</button><button className={tab==='safeguarding'?'active':''} onClick={()=>{setTab('safeguarding');setSelected(null)}}><LockKeyhole/>Safeguarding</button></div>{tab==='safeguarding'&&<span className="restricted"><LockKeyhole/>Restricted records</span>}</div>{query.isLoading?<Loading/>:query.error?<DataError message={query.error.message}/>:rows?.length?<div className="case-list">{rows.map(r=><article key={r.id} className="clickable" onClick={()=>setSelected(r)}><span className={`case-icon ${r.severity||r.risk_level}`}><ShieldAlert/></span><div className="case-title"><strong>{r.incident_type||r.concern_type}</strong><span>{r.service_user?.full_name||'No person linked'}</span></div><div><small>{tab==='incidents'?'Occurred':'Raised'}</small><strong>{new Date(r.occurred_at||r.created_at).toLocaleDateString('en-GB')}</strong></div><div><small>Severity</small><Status value={r.severity||r.risk_level}/></div><div><small>Status</small><Status value={r.status}/></div><button className="btn small">Open case</button></article>)}</div>:<Empty text={tab==='incidents'?'No incidents recorded':'No safeguarding concerns recorded'}/>} {(creating||selected)&&<Modal title={tab==='incidents'?(selected?'Review incident':'Report incident'):(selected?'Review safeguarding concern':'Record safeguarding concern')} onClose={close}>{tab==='incidents'?<>{selected&&actions.data?.some(x=>x.incident_id===selected.id)&&<div className="record-detail action-list"><h3>Follow-up actions</h3>{actions.data.filter(x=>x.incident_id===selected.id).map(x=><label key={x.id}><input type="checkbox" checked={Boolean(x.completed_at)} onChange={e=>void updateAction.mutate({id:x.id,completed_at:e.target.checked?new Date().toISOString():null})}/><span><strong>{x.action}</strong><small>{x.due_date?`Due ${new Date(x.due_date).toLocaleDateString('en-GB')}`:'No due date'}</small></span></label>)}</div>}<IncidentForm people={people.data??[]} record={selected??undefined} onClose={close}/></>:<SafeguardingForm people={people.data??[]} record={selected??undefined} onClose={close}/>}</Modal>}</>
}
